ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS client_request_id uuid,
  ADD COLUMN IF NOT EXISTS service_name_snapshot text,
  ADD COLUMN IF NOT EXISTS service_code_snapshot integer,
  ADD COLUMN IF NOT EXISTS category_name_snapshot text,
  ADD COLUMN IF NOT EXISTS service_description_snapshot text,
  ADD COLUMN IF NOT EXISTS requirements_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS delivery_time_snapshot text,
  ADD COLUMN IF NOT EXISTS admin_notes text,
  ADD COLUMN IF NOT EXISTS refunded_amount numeric(14,2) NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS orders_user_client_request_key
  ON public.orders(user_id, client_request_id)
  WHERE client_request_id IS NOT NULL;

CREATE TABLE public.payment_methods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('crypto', 'upi', 'inr')),
  network text,
  instructions text,
  destination text,
  min_amount numeric(14,2) NOT NULL DEFAULT 1 CHECK (min_amount > 0),
  max_amount numeric(14,2) NOT NULL DEFAULT 10000 CHECK (max_amount >= min_amount),
  is_enabled boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.payment_methods TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payment_methods TO authenticated;
GRANT ALL ON public.payment_methods TO service_role;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "customers read enabled payment methods" ON public.payment_methods
  FOR SELECT TO authenticated USING (is_enabled OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins manage payment methods" ON public.payment_methods
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER payment_methods_updated_at BEFORE UPDATE ON public.payment_methods
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.deposit_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  payment_method_id uuid NOT NULL REFERENCES public.payment_methods(id),
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  payment_reference text NOT NULL,
  proof_path text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  customer_notes text,
  admin_notes text,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  transaction_id uuid REFERENCES public.transactions(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.deposit_requests TO authenticated;
GRANT UPDATE ON public.deposit_requests TO authenticated;
GRANT ALL ON public.deposit_requests TO service_role;
ALTER TABLE public.deposit_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "customers read own deposits" ON public.deposit_requests
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "customers create own deposits" ON public.deposit_requests
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id AND status = 'pending');
CREATE POLICY "admins read deposits" ON public.deposit_requests
  FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins update deposits" ON public.deposit_requests
  FOR UPDATE TO authenticated USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX deposit_requests_user_created_idx ON public.deposit_requests(user_id, created_at DESC);
CREATE INDEX deposit_requests_status_created_idx ON public.deposit_requests(status, created_at DESC);
CREATE TRIGGER deposit_requests_updated_at BEFORE UPDATE ON public.deposit_requests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.admin_activity_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.admin_activity_logs TO authenticated;
GRANT ALL ON public.admin_activity_logs TO service_role;
ALTER TABLE public.admin_activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins read activity logs" ON public.admin_activity_logs
  FOR SELECT TO authenticated USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "admins create activity logs" ON public.admin_activity_logs
  FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'admin') AND actor_id = auth.uid());
CREATE INDEX admin_activity_created_idx ON public.admin_activity_logs(created_at DESC);

CREATE TABLE public.website_settings (
  id text PRIMARY KEY DEFAULT 'primary' CHECK (id = 'primary'),
  brand_name text NOT NULL DEFAULT 'Neo Mart',
  logo_url text,
  support_email text,
  announcement text,
  announcement_enabled boolean NOT NULL DEFAULT false,
  currency text NOT NULL DEFAULT 'USD',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.website_settings TO anon, authenticated;
GRANT INSERT, UPDATE ON public.website_settings TO authenticated;
GRANT ALL ON public.website_settings TO service_role;
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public reads website settings" ON public.website_settings
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins manage website settings" ON public.website_settings
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TRIGGER website_settings_updated_at BEFORE UPDATE ON public.website_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
INSERT INTO public.website_settings (id) VALUES ('primary') ON CONFLICT (id) DO NOTHING;

CREATE TABLE public.provider_services (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
  provider_service_id text NOT NULL,
  source_name text NOT NULL,
  source_category text NOT NULL,
  source_type text,
  source_rate numeric(18,6) NOT NULL DEFAULT 0,
  min_quantity integer NOT NULL DEFAULT 1,
  max_quantity integer NOT NULL DEFAULT 1,
  refill_available boolean,
  cancel_available boolean,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  sync_status text NOT NULL DEFAULT 'staged' CHECK (sync_status IN ('staged', 'approved', 'rejected', 'removed')),
  mapped_service_id uuid REFERENCES public.services(id) ON DELETE SET NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(provider_id, provider_service_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.provider_services TO authenticated;
GRANT ALL ON public.provider_services TO service_role;
ALTER TABLE public.provider_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins manage provider services" ON public.provider_services
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX provider_services_sync_idx ON public.provider_services(provider_id, sync_status, last_seen_at DESC);
CREATE TRIGGER provider_services_updated_at BEFORE UPDATE ON public.provider_services
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.place_order_atomic(
  _service_id uuid,
  _target_link text,
  _quantity integer,
  _notes text,
  _client_request_id uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _user_id uuid := auth.uid();
  _service public.services%ROWTYPE;
  _profile public.profiles%ROWTYPE;
  _category_name text;
  _total numeric(14,2);
  _new_balance numeric(14,2);
  _order public.orders%ROWTYPE;
BEGIN
  IF _user_id IS NULL THEN RAISE EXCEPTION 'Unauthorized'; END IF;
  SELECT * INTO _service FROM public.services
    WHERE id = _service_id AND is_active = true AND is_archived = false;
  IF NOT FOUND THEN RAISE EXCEPTION 'This service is no longer available.'; END IF;
  IF _quantity < _service.min_quantity OR _quantity > _service.max_quantity THEN
    RAISE EXCEPTION 'Quantity must be between % and %.', _service.min_quantity, _service.max_quantity;
  END IF;
  SELECT * INTO _profile FROM public.profiles WHERE id = _user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Customer profile not found.'; END IF;
  _total := round((_service.price_per_unit * _quantity)::numeric, 2);
  IF _profile.balance < _total THEN RAISE EXCEPTION 'Not enough wallet balance for this order.'; END IF;
  SELECT name INTO _category_name FROM public.service_categories WHERE id = _service.category_id;
  INSERT INTO public.orders (
    user_id, service_id, target_link, quantity, unit_price, total_amount, notes, status,
    client_request_id, service_name_snapshot, service_code_snapshot, category_name_snapshot,
    service_description_snapshot, requirements_snapshot, delivery_time_snapshot
  ) VALUES (
    _user_id, _service.id, _target_link, _quantity, _service.price_per_unit, _total, NULLIF(_notes, ''), 'pending',
    _client_request_id, _service.name, _service.service_code, _category_name,
    _service.description, _service.features, _service.delivery_time
  )
  ON CONFLICT (user_id, client_request_id) WHERE client_request_id IS NOT NULL DO UPDATE SET client_request_id = EXCLUDED.client_request_id
  RETURNING * INTO _order;
  IF _order.created_at < now() - interval '5 seconds' THEN
    RETURN jsonb_build_object('orderId', _order.id, 'orderNumber', _order.order_number, 'balance', _profile.balance, 'duplicate', true);
  END IF;
  _new_balance := _profile.balance - _total;
  UPDATE public.profiles SET balance = _new_balance WHERE id = _user_id;
  INSERT INTO public.transactions(user_id, type, amount, balance_after, description, reference, status)
  VALUES (_user_id, 'order', -_total, _new_balance, _service.name || ' × ' || _quantity, _order.id::text, 'completed');
  RETURN jsonb_build_object('orderId', _order.id, 'orderNumber', _order.order_number, 'balance', _new_balance, 'duplicate', false);
END;
$$;
REVOKE ALL ON FUNCTION public.place_order_atomic(uuid, text, integer, text, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.place_order_atomic(uuid, text, integer, text, uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.review_deposit_atomic(
  _deposit_id uuid,
  _decision text,
  _admin_notes text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _admin_id uuid := auth.uid();
  _deposit public.deposit_requests%ROWTYPE;
  _balance numeric(14,2);
  _transaction_id uuid;
BEGIN
  IF _admin_id IS NULL OR NOT public.has_role(_admin_id, 'admin') THEN RAISE EXCEPTION 'Forbidden'; END IF;
  IF _decision NOT IN ('approved', 'rejected') THEN RAISE EXCEPTION 'Invalid decision'; END IF;
  SELECT * INTO _deposit FROM public.deposit_requests WHERE id = _deposit_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Deposit request not found'; END IF;
  IF _deposit.status <> 'pending' THEN RAISE EXCEPTION 'This deposit has already been reviewed'; END IF;
  IF _decision = 'approved' THEN
    SELECT balance INTO _balance FROM public.profiles WHERE id = _deposit.user_id FOR UPDATE;
    _balance := _balance + _deposit.amount;
    UPDATE public.profiles SET balance = _balance WHERE id = _deposit.user_id;
    INSERT INTO public.transactions(user_id, type, amount, balance_after, description, reference, status)
    VALUES (_deposit.user_id, 'deposit', _deposit.amount, _balance, 'Approved manual deposit', _deposit.id::text, 'completed')
    RETURNING id INTO _transaction_id;
  END IF;
  UPDATE public.deposit_requests
    SET status = _decision, admin_notes = NULLIF(_admin_notes, ''), reviewed_by = _admin_id,
        reviewed_at = now(), transaction_id = _transaction_id
    WHERE id = _deposit_id;
  INSERT INTO public.admin_activity_logs(actor_id, action, entity_type, entity_id, details)
    VALUES (_admin_id, 'deposit_' || _decision, 'deposit_request', _deposit_id::text,
      jsonb_build_object('amount', _deposit.amount, 'user_id', _deposit.user_id));
  RETURN jsonb_build_object('ok', true, 'status', _decision, 'balance', _balance, 'transactionId', _transaction_id);
END;
$$;
REVOKE ALL ON FUNCTION public.review_deposit_atomic(uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.review_deposit_atomic(uuid, text, text) TO authenticated;